[package]
name = "setcover"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
name = "_setcover_lib"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21.2", features = ["extension-module"] }
setcover-core = { path = "../crates/setcover-core" }
