[package]
name = "set_cover"
version = "0.1.0"
authors = ["Matthias kaeding <kaedingmatthias@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.8.5"
bitvec = "1"

[dev-dependencies]
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
