[package]
name = "set_cover"
version = "0.1.0"
authors = ["Matthias kaeding <kaedingmatthias@gmail.com>"]
edition = "2018"

[lib]
name = "set_cover"
crate-type = ["cdylib", "rlib"]

[dependencies]
bitvec = "1"
pyo3 = { version = "0.19", features = ["extension-module"] }

[dev-dependencies]
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }

[[example]]
name = "benchmark"
path = "scripts/benchmark/benchmark.rs"
